# Generated by Django 5.0.6 on 2024-09-27 20:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='complete',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='cdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
