# Generated by Django 5.0.6 on 2024-09-27 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0002_remove_tasklist_complete_tasklist_cdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
