# Generated by Django 5.0.6 on 2024-09-27 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0004_remove_tasklist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='cdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
